CREATE DATABASE ZW3;
USE ZW3;
ALTER DATABASE ZW3 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;


CREATE TABLE HANZI(
  hanzi_id INT NOT NULL AUTO_INCREMENT,
  topic_id INT NOT NULL,
  word MEDIUMTEXT NOT NULL,
  pinyin MEDIUMTEXT NOT NULL,
  meaning MEDIUMTEXT NOT NULL,
  img_id INT NOT NULL,
  fact MEDIUMTEXT NOT NULL,
  year INT NOT NULL,
  PRIMARY KEY(hanzi_id)
);

CREATE TABLE TOPIC(
  topic_id INT NOT NULL AUTO_INCREMENT,
  topic_name TINYTEXT NOT NULL,
  year INT NOT NULL,
  PRIMARY KEY(topic_id)
);

CREATE TABLE IMG(
  img_id INT NOT NULL AUTO_INCREMENT,
  img_name TINYTEXT NOT NULL,
  PRIMARY KEY(img_id)
);

CREATE TABLE SENSTRU(
  struct_id INT NOT NULL AUTO_INCREMENT,
  struct MEDIUMTEXT NOT NULL,
  struct_description MEDIUMTEXT NOT NULL,
  PRIMARY KEY(struct_id)
);

CREATE TABLE SENEXAMPLE(
  sen_id INT NOT NULL AUTO_INCREMENT,
  struct_id INT NOT NULL,
  sen MEDIUMTEXT NOT NULL,
  PRIMARY KEY(sen_id)
);

CREATE TABLE SHADOW(
  txt_id INT NOT NULL AUTO_INCREMENT,
  title MEDIUMTEXT NOT NULL,
  about MEDIUMTEXT NOT NULL,
  txt LONGTEXT NOT NULL,
  PRIMARY KEY(txt_id)
);

INSERT INTO `IMG` (`img_id`, `img_name`) VALUES ('1', 'white.png');
